
name: Lint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Luacheck + dependencies
      run: sudo apt install lua-check

    - name: Run linter
      run: luacheck --no-self --no-global --no-max-line-length ccpm.lua
